function hCont = InitializeControlGui

%% ***Move to MicroscopeControlGui***
% Microscope Controls [left bottom width height]

global mP

if isempty(mP)
   InitializeMicroscopeProperties;
end

hCont.hControlPanel = figure('Name','MATLAB Micro-Manager',...
                             'Units','Pixels',...
                             'Position',mP.posControl);
                         
% hCont.hResetFunctions = uicontrol('Parent',hCont.hControlPanel,...
%                                  'Style','pushbutton',...
%                                  'String','Reset Fig',...
%                                  'Units','normalized',...
%                                  'Position',[0.94,0.4125,0.05,0.05]);

%% Stage Position Control Panel

hCont.hStagePosPanel = uipanel('Parent', hCont.hControlPanel,...
                              'Title', 'Stage Position',...
                              'Units','normalized',...
                              'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                              'BorderType','line',...
                              'Position',[0.003, 0.4125,0.497,0.575]);

hCont.hFocusContAx = axes('Parent',hCont.hStagePosPanel,...
                          'Position',[0.31,0.6,0.075,0.35]);

hCont.hStageContAx = axes('Parent',hCont.hStagePosPanel,...
                          'Position',[0.01,0.6,0.35*4/5,0.35]);

hCont.hNavImAx = axes('Parent',hCont.hStagePosPanel,...
                        'Units','normalized',...
                        'Position',[0.35,0.01,0.8*4/5,0.8/1.4884]);
                    
hCont.hNavContAx = axes('Parent',hCont.hStagePosPanel,...
                        'Units','normalized',...
                        'Visible','off',...
                        'Position',[0.35,0.01,0.8*4/5,0.8/1.4884]);
 
focusIm     = imread('Focus Control.tif');                     
stageArrows = imread('Stage Arrows.tif');
navIm       = imread('Drug 1 chamber Slide Gasket MakerDesign v1.jpg');

hCont.FocusContIm = image(focusIm, 'Parent',hCont.hFocusContAx);
set(hCont.hFocusContAx,'XTick',[],'YTick',[],'Visible','off');

hCont.hStageContIm = image(stageArrows,'Parent',hCont.hStageContAx);
set(hCont.hStageContAx,'XTick',[],'YTick',[],'Visible','off');

hCont.hNavContIm   = image(navIm,'Parent',hCont.hNavImAx, 'HitTest','off');
set(hCont.hNavImAx,'XTick',[],'YTick',[],'Visible','off', 'HitTest','off');

% images 1,2 are 670pix/58500um  
pixum = 690/(4500*13);
imDim = size(navIm);
xMax =  imDim(2)/pixum;
yMax =  imDim(1)/pixum;
xOrigin = 99/pixum;
yOrigin = 110/pixum;
set(hCont.hNavContAx,'XTick',[],'YTick',[],'PickableParts','all','HitTest','on','YDir','reverse',...
                      'XLim',[0,xMax]-xOrigin, 'YLim',[0,yMax]-yOrigin);

cols = 0:4500:4500*13;
rows = 0:4500:4500*7;
spacing =  4500;
xoffset = -2250;
yoffset = -2250;
% rows = 0:7;
% cols = 0:13;
% spacing = 53;
% xoffset = 74;
% yoffset = 85;
radius = spacing;
hCont.hNavCircles = gobjects(numel(rows)*numel(cols),1);

cnt = 1;
for row = rows
    for col = cols

        cCenters(cnt,:) = [col+xoffset, row+yoffset, radius,radius];
        hCont.hNavCircles(cnt) = rectangle('Position',cCenters(cnt,:),...
                                               'EdgeColor',[1 0 0],...
                                               'Curvature',[1,1],...
                                               'Parent',hCont.hNavContAx,...
                                               'HitTest','off');
                                           
       

        cnt = cnt+1;
    end
  
end

mP.cCenters = cCenters;

hCont.htextX = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','text',...
                                  'String','x = ',...
                                  'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(1,:)-[0,-0.06,0,0]);

hCont.hStagePosX = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','edit',...
                                  'String',num2str(500),...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(1,:));
                              
hCont.htextY = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','text',...
                                  'String','y = ',...
                                  'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(2,:)-[0,-0.06,0,0]);
                              
hCont.hStagePosY = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','edit',...
                                  'String',num2str(500),...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(2,:));
                              
hCont.htextZ = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','text',...
                                  'String','z = ',...
                                  'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(3,:)-[0,-0.06,0,0]);
                              
hCont.hStagePosZ = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','edit',...
                                  'String',num2str(500),...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(3,:));
                              
hCont.htextWell = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','text',...
                                  'String','Well = ',...
                                  'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(4,:)-[0,-0.06,0,0]);
                              
hCont.hStagePosWell = uicontrol('Parent',hCont.hStagePosPanel,...
                                'Style','edit',...
                                'String',[],...
                                'Units','normalized',...
                                'Position', mP.EditXYZPos(4,:));                      
                            
hCont.htextOriginX = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','text',...
                                  'String','X Origin',...
                                  'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(5,:)-[0,-0.06,0,0]);

hCont.hStageOriginX = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','edit',...
                                  'String',num2str(mP.XYZOrigin(1)),...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(5,:));
                              
hCont.htextOriginY = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','text',...
                                  'String','Y Origin',...
                                  'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(6,:)-[0,-0.06,0,0]);
                              
hCont.hStageOriginY = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','edit',...
                                  'String',num2str(mP.XYZOrigin(2)),...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(6,:));
                              
hCont.htextOriginZ = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','text',...
                                  'String','Z Origin',...
                                  'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(7,:)-[0,-0.06,0,0]);
                              
hCont.hStageOriginZ = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','edit',...
                                  'String',num2str(mP.XYZOrigin(3)),...
                                  'Units','normalized',...
                                  'Position', mP.EditXYZPos(7,:));
                              
                              
hCont.htextOriginSet = uicontrol('Parent',hCont.hStagePosPanel,...
                                  'Style','text',...
                                  'String','Origin',...
                                  'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                                  'Units','normalized',...
                                  'Position', mP.sethOriginPos-[0,-0.06,0,0]);
                              
hCont.hStageOriginSet = uicontrol('Parent',hCont.hStagePosPanel,...
                                 'Style','pushbutton',...
                                  'String','Set',...
                                  'Units','Normalized',...
                                  'Position',mP.sethOriginPos);

hCont.hStageGoOrigin = uicontrol('Parent',hCont.hStagePosPanel,...
                                 'Style','pushbutton',...
                                  'String','Go Origin',...
                                  'Units','Normalized',...
                                  'Position',mP.sethGoOrigin);
mP.posSlideSel   = [0.05, 0.25, 0.2, 0.1];

hCont.hSlideSelect = uicontrol('Parent',hCont.hStagePosPanel,...
                               'Style','popupmenu',...
                               'String','Single|5 Chamber|24 Well',...
                               'Units','Normalized',...
                               'Position',mP.posSlideSel);
                              

hCont.hRunODELAY = uicontrol('Parent',hCont.hStagePosPanel,...
                             'Style','togglebutton',...
                             'String','ODELAY!!!',...
                             'Units','Normalized',...
                             'Position',mP.sethRunODELAY);

%% Illumination Control Panel [left bottom width height]

hCont.hIllumPanel = uipanel('Parent',hCont.hControlPanel,...
                            'Title', 'Illumination Control',...
                            'Units','normalized',...
                            'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                            'BorderType','line',...
                            'Position',[0.5125, 0.4125,0.25,0.3]);

hCont.hTransLamp = uicontrol('Parent',hCont.hIllumPanel,...
                             'Style','slider',...
                             'min',0,'max',1000,...
                             'SliderStep',[1/1000 10/1000],...
                             'value',550,...
                             'Units','normalized',...
                             'Position',[0.05,0.15, 0.1, 0.8]);
                         
hCont.hTransLampEdit = uicontrol('Parent',hCont.hIllumPanel,...
                             'Style','edit',...
                             'Units','normalized',...
                             'String',num2str(round(get(hCont.hTransLamp,'value'))),...
                             'Position',[0.025,0.025, 0.15, 0.1]);

hCont.hTransApp = uicontrol('Parent',hCont.hIllumPanel,...
                            'Style','Slider',...
                            'value',19,...
                            'min',1,'max',46,...
                            'SliderStep',[1/46 1/46],...
                            'Units','normalized',...
                            'Position',[0.25,0.15, 0.1, 0.8]);

hCont.hTransAppEdit = uicontrol('Parent',hCont.hIllumPanel,...
                             'Style','edit',...
                             'Units','normalized',...
                             'String',num2str(round(get(hCont.hTransApp,'value'))),...
                             'Position',[0.225,0.025, 0.15, 0.1]);
 
hCont.hFluorApp = uicontrol('Parent',hCont.hIllumPanel,...
                            'Style','Slider',...
                            'value',12,...
                            'min',1,'max',12,...
                            'SliderStep',[1/12 1/12],...
                            'Units','normalized',...
                            'Position',[0.45,0.15, 0.1, 0.8]);

hCont.hFluorAppEdit = uicontrol('Parent',hCont.hIllumPanel,...
                             'Style','edit',...
                             'Units','normalized',...
                             'String',num2str(round(get(hCont.hFluorApp,'value'))),...
                             'Position',[0.425,0.025, 0.15, 0.1]);

hCont.hTransShutter = uicontrol('Parent',hCont.hIllumPanel,...
                                'Style','togglebutton',...
                                'Units','normalized',...
                                'String','Trans',...
                                'Position',[0.65,0.6,0.3,0.3]);

hCont.hFluorShutter = uicontrol('Parent',hCont.hIllumPanel,...
                                'Style','togglebutton',...
                                'Units','normalized',...
                                'String','Fluor',...
                                'Position',[0.65,0.1,0.3,0.3]);
                            
hCont.hShutterText = uicontrol('Parent',hCont.hIllumPanel,...
                                  'Style','text',...
                                  'String',{'Shutter';'Control'},...
                                  'BackgroundColor',get(hCont.hIllumPanel,'BackgroundColor'),...
                                  'Units','normalized',...
                                  'Position',[0.65,0.9,0.3,0.1]);
                     
%% Cube Control selection and highlight 0-5 
hCont.hCubePanel = uipanel('Parent',hCont.hControlPanel,...
                            'Title', 'Cube Selection',...
                            'Units','normalized',...
                            'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                            'BorderType','line',...
                            'Position',[0.003, 0.005,0.76,0.4]);

hCont.hFocusText = uicontrol('Parent',hCont.hCubePanel,...
                            'Style', 'text',...
                            'String', 'Focus Exp',...
                            'Units','normalized',...
                            'Position',mP.FocusPos(1,:)-[0.125,0,0,0],...
                            'BackgroundColor',get(hCont.hCubePanel, 'BackgroundColor'));

hCont.hExpText = uicontrol('Parent',hCont.hCubePanel,...
                            'Style', 'text',...
                            'String', 'Exp Time',...
                            'Units','normalized',...
                            'Position',mP.ExpPos(1,:)-[0.125,0,0,0],...
                            'BackgroundColor',get(hCont.hCubePanel, 'BackgroundColor'));

hCont.hRecordText = uicontrol('Parent',hCont.hCubePanel,...
                              'Style', 'text',...
                              'String', 'Record Channel',...
                              'Units','normalized',...
                              'Position',mP.ExpPos(1,:)-[0.175,0.7,-0.1,0],...
                              'BackgroundColor',get(hCont.hCubePanel, 'BackgroundColor'));


for n = 1:7
    hCont.hCubeSel(n) = uicontrol('Parent',hCont.hCubePanel,...
                                  'Style','togglebutton',...
                                  'value',mP.CubeEngaged(n),...
                                  'BackgroundColor',mP.CubeColor(n,:),...
                                  'Units','normalized',...
                                  'String',mP.stateNames{n},...
                                  'FontWeight','bold',...
                                  'Position',mP.CubePos(n,:));
                              
    hCont.hRecordSel(n) = uicontrol('Parent',hCont.hCubePanel,...
                                    'Style','togglebutton',...
                                    'value',mP.CubeEngaged(n),...
                                    'BackgroundColor',mP.RecColor(n,:),...
                                    'Units','normalized',...
                                    'String',mP.stateNames{n},...
                                    'Position',mP.RecPos(n,:));
                              
   hCont.hCubeFocus(n) = uicontrol('Parent',hCont.hCubePanel,...
                                  'Style','edit',...
                                  'String',[num2str(mP.ExpTime(n))],...
                                  'Units','normalized',...
                                  'Position',mP.FocusPos(n,:));
                              
   hCont.hCubeExp(n) = uicontrol('Parent',hCont.hCubePanel,...
                                  'Style','edit',...
                                  'String',[num2str(mP.ExpTime(n))],...
                                  'Units','normalized',...
                                  'Position',mP.ExpPos(n,:));
end
 
%% Camera Control Snap Image/Continous

hCont.hCameraPanel  = uipanel('Parent',hCont.hControlPanel,...
                              'Title', 'Camera',...
                              'Units','normalized',...
                              'BackgroundColor',get(hCont.hControlPanel,'Color')+0.05,...
                              'BorderType','line',...
                              'Position',[0.775, 0.4125,0.10, 0.3]);

hCont.hCameraSnap = uicontrol('Parent', hCont.hCameraPanel,...
                              'Style', 'pushbutton',...
                              'Units','normalized',...
                              'String','Expose',...
                              'Position',[0.1,0.1,0.8,0.3]);

hCont.hCameraFocus = uicontrol('Parent', hCont.hCameraPanel,...
                              'Style', 'togglebutton',...
                              'Units','normalized',...
                              'String','Focus',...
                              'Position',[0.1,0.6,0.8,0.3]);
                          
%% Autofocus Control Panel

hCont.hAutofocusPanel = uipanel('Parent', hCont.hControlPanel,...
                                'Title', 'AutoFocus',...
                                'Units', 'normalized',...
                                'BackgroundColor', get(hCont.hControlPanel,'Color')+0.05,...
                                'BorderType', 'line',...
                                'Position',[0.5125, 0.725,0.25,0.2625]);
                            
hCont.hAutofocusRangeText = uicontrol('Parent',hCont.hAutofocusPanel,...
                                   'Style','text',...
                                   'String','z Range',...
                                   'Units','normalized',...
                                   'BackgroundColor', get(hCont.hAutofocusPanel,'BackgroundColor'),...
                                   'Position',[0.01,0.37,0.29,0.15]);
                               
hCont.hAutofocusStepsText  = uicontrol('Parent',hCont.hAutofocusPanel,...
                                   'Style','text',...
                                   'String','Focus Steps',...
                                   'Units','normalized',...
                                   'BackgroundColor', get(hCont.hAutofocusPanel,'BackgroundColor'),...
                                   'Position',[0.005,0.2,0.35,0.15]);   
                               
hCont.hAutofocusTargetIncText  =uicontrol('Parent',hCont.hAutofocusPanel,...
                                   'Style','text',...
                                   'String','Target Inc',...
                                   'Units','normalized',...
                                   'BackgroundColor', get(hCont.hAutofocusPanel,'BackgroundColor'),...
                                   'Position',[0.01,0.02,0.29,0.15]); 

hCont.hAutofocusButton = uicontrol('Parent',hCont.hAutofocusPanel,...
                                 'Style','pushbutton',...
                                 'Units', 'normalized',...
                                 'String','AF Ph1',...
                                 'Position',[0.35,0.75,0.29,0.2]);
                                                    
hCont.hAutofocusSelect = uicontrol('Parent',hCont.hAutofocusPanel,...
                                    'Style','popupmenu',...
                                    'Value',19,...
                                    'String',mP.AutofocusMenu,...
                                    'Units','normalized',...
                                    'Position',[0.35,0.57,0.29,0.15]);
 
 hCont.hAutofocusRange = uicontrol('Parent',hCont.hAutofocusPanel,...
                                   'Style','edit',...
                                   'String',num2str(mP.zRange),...
                                   'Units','normalized',...
                                   'Position',[0.35,0.375,0.29,0.15]);
                                                    
hCont.hAutofocusSteps  = uicontrol('Parent',hCont.hAutofocusPanel,...
                                   'Style','edit',...
                                   'String',num2str(mP.numSteps),...
                                   'Units','normalized',...
                                   'Position',[0.35,0.2125,0.29,0.15]);
                             
hCont.hAutofocusTargetInc  = uicontrol('Parent',hCont.hAutofocusPanel,...
                                   'Style','edit',...
                                   'String',num2str(mP.targetIncrement),...
                                   'Units','normalized',...
                                   'Position',[0.35,0.05,0.29,0.15]);  
                
hCont.hAutofocusButton2 = uicontrol('Parent',hCont.hAutofocusPanel,...
                                 'Style','pushbutton',...
                                 'Units', 'normalized',...
                                 'String','AF Ph2',...
                                 'Position',[0.65,0.75,0.29,0.2]);
                               
hCont.hAutofocusSelect2 = uicontrol('Parent',hCont.hAutofocusPanel,...
                                    'Style','popupmenu',...
                                    'Value',19,...
                                    'String',mP.AutofocusMenu,...
                                    'Units','normalized',...
                                    'Position',[0.65,0.57,0.29,0.15]);
 
 hCont.hAutofocusRange2 = uicontrol('Parent',hCont.hAutofocusPanel,...
                                   'Style','edit',...
                                   'String',num2str(mP.zRange2),...
                                   'Units','normalized',...
                                   'Position',[0.65,0.375,0.29,0.15]);
                               
hCont.hAutofocusSteps2  = uicontrol('Parent',hCont.hAutofocusPanel,...
                                   'Style','edit',...
                                   'String',num2str(mP.numSteps2),...
                                   'Units','normalized',...
                                   'Position',[0.65,0.2125,0.29,0.15]);
                               
hCont.hAutofocusTargetInc2  = uicontrol('Parent',hCont.hAutofocusPanel,...
                                   'Style','edit',...
                                   'String',num2str(mP.targetIncrement2),...
                                   'Units','normalized',...
                                   'Position',[0.65,0.05,0.29,0.15]); 
                                                             
%% Lens Display and Reset

hCont.hLensPannel =  uipanel('Parent', hCont.hControlPanel,...
                                'Title', 'Lens',...
                                'Units', 'normalized',...
                                'BackgroundColor', get(hCont.hControlPanel,'Color')+0.05,...
                                'BorderType', 'line',...
                                'Position',[0.885, 0.4125,0.10, 0.3]);
                            
hCont.hLensMenu    = uicontrol('Parent',hCont.hLensPannel,...
                                   'Style','popupmenu',...
                                   'String',mP.LenseMenu,...
                                   'Units','normalized',...
                                   'BackgroundColor', get(hCont.hAutofocusPanel,'BackgroundColor'),...
                                   'Position',[0.1,0.6,0.8,0.2]);
                               
hCont.hResetFunctions = uicontrol('Parent',hCont.hLensPannel,...
                                 'Style','pushbutton',...
                                 'String','Test Func',...
                                 'Units','normalized',...
                                 'Position',[0.1,0.1,0.8,0.3]);

%% Slice Pannel
hCont.hSlicePannel =  uipanel('Parent', hCont.hControlPanel,...
                                'Title', 'Slice/Tile Control',...
                                'Units', 'normalized',...
                                'BackgroundColor', get(hCont.hControlPanel,'Color')+0.05,...
                                'BorderType', 'line',...
                                'Position',[0.775,0.725,0.21,0.2625]);
                            
hCont.hTileSelect    = uicontrol('Parent',hCont.hSlicePannel,...
                                   'Style','popupmenu',...
                                   'String','1|9',...
                                   'Value',2,...
                                   'Units','normalized',...
                                   'Position',[0.1,0.75,0.29,0.2]);  
                               
hCont.hNumSlices    = uicontrol('Parent',hCont.hSlicePannel,...
                                   'Style','edit',...
                                   'String','1',...
                                   'Units','normalized',...
                                   'Position',[0.65,0.375,0.29,0.15]); 

hCont.hSlicesThick    = uicontrol('Parent',hCont.hSlicePannel,...
                                   'Style','edit',...
                                   'String','1.5',...
                                   'Units','normalized',...
                                   'Position',[0.65,0.2125,0.29,0.15]); 
                               
hCont.hTotalThickness    = uicontrol('Parent',hCont.hSlicePannel,...
                                   'Style','text',...
                                   'String','1.5',...
                                   'Units','normalized',...
                                   'Position',[0.65,0.05,0.29,0.15]);                                
                               
%% Update Position
hCont.hPositionPannel =  uipanel('Parent', hCont.hControlPanel,...
                                'Title', 'Position List',...
                                'Units', 'normalized',...
                                'BackgroundColor', get(hCont.hControlPanel,'Color')+0.05,...
                                'BorderType', 'line',...
                                'Position',[0.775,0.005,0.21,0.4]);     
                            
hCont.hPosList = uicontrol('Parent',hCont.hPositionPannel,...
                                    'Style','listbox',...
                                    'Value',1,...
                                    'String',mP.wellID,...
                                    'Units','normalized',...
                                    'Position',[0.5,0.01,0.48,0.975]); 
                                
hCont.hLoadList = uicontrol('Parent',hCont.hPositionPannel,...
                                    'Style','pushbutton',...
                                    'String','Load List',...
                                    'Units','normalized',...
                                    'Position',[0.05,0.8,0.4,0.15]);

hCont.hUpdatePos = uicontrol('Parent',hCont.hPositionPannel,...
                                    'Style','pushbutton',...
                                    'String','Update Pos',...
                                    'Units','normalized',...
                                    'Position',[0.05,0.6,0.4,0.15]);
                                
hCont.hMovePrev = uicontrol('Parent',hCont.hPositionPannel,...
                                    'Style','pushbutton',...
                                    'String','Prev',...
                                    'Units','normalized',...
                                    'Position',[0.05,0.3,0.4,0.15]);

hCont.hMovNext = uicontrol('Parent',hCont.hPositionPannel,...
                                    'Style','pushbutton',...
                                    'String','Next',...
                                    'Units','normalized',...
                                    'Position',[0.05,0.1,0.4,0.15]);
 
end